### ISSUE TITLE
Default width generates 1x1 image

### ISSUE THREAD

**Issue by sophietk** [excellenteasy/grunt-image-resize#28]
Hi,

The plugin allowed specifying only width -or height- to maintain the aspect ratio of the image. Now, that causes the generated image size to be 1x1.

Since the commit aheckmann/gm@781fb82 changes the gm resize implementation, a 0-value is considered as a valid width/height. The grunt-image-resize should not provide '0' as default value anymore. Instead '' (empty string) should do the job.

**Comment by pazzypunk** [comment]
@sophietk THANK YOU THANK YOU THANK YOU. I had this problem for weeks and had no idea what the issue was. You need to pass an empty string for height, too.

**Comment by nadnoslen** [comment]
Yes thank you @sophietk.  This issue got me a month ago and had me vexed.  I think we all need to find a new library considering this one is no longer being maintained.

**Comment by thebiltheory** [comment]
@sophietk Sank U !
