### ISSUE TITLE
Fatal error: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by DavidKk** [excellenteasy/grunt-image-resize#9]
MAC AIR OS 10.8.4

Fatal error: Cannot read property 'width' of undefined

![image](https://f.cloud.github.com/assets/4200041/1466109/e38fc374-456b-11e3-8c68-9ed5e75c1d34.png)

![image](https://f.cloud.github.com/assets/4200041/1466122/2c24c17a-456c-11e3-8db2-e4b25fb385f7.png)

**Comment by caiobleggi** [comment]
Thanks @thusoy for solving this. 

Just complementing the solution for who doesn't know [to change the imagemagick path on Windows 7+](http://www.computerhope.com/issues/ch000549.htm). Be sure of change only the ```C:/Program Files/ImageMagick-(version)``` path to your grunt.js folder. (In my case, had many others values on the PATH variable).

:clap::clap::sweat_smile:
